### ISSUE TITLE
Strategy for aligning with BioTop and SIO

### ISSUE THREAD

**Issue by cmungall** [rctauber/Experimental-OBO-Core#1]
Should we include xrefs or a separate mapping table?

Should we first look at these and evaluate them w.r.t whether parts can be lifted or even direct reuse?

**Comment by cmungall** [comment]
Also consider allotrope here

**Comment by beckyjackson** [comment]
Migrated to https://github.com/OBOFoundry/Experimental-OBO-Core/issues/22
