### ISSUE TITLE
Standardize how we indicate the relationship between a core class and its matching OBO one

### ISSUE THREAD

**Issue by cmungall** [rctauber/Experimental-OBO-Core#2]
Currently we have been making notes as rdfs:comments but we should do this in a better way

If we believe they are truly equivalent then equivalentClasses is appropriate - however, this is a pain to work with in protege (since you induce a class declaration). I would vote for editing as a skos:exactMatch (we can avoid declaring a class). It could be converted to equivalence during release

For close matches, skos:closeMatch, otherwise rdfs:seeAlso?

Or we could make our own vocabulary for this?

**Comment by cmungall** [comment]
Note we should also have a pipeline where we do an integration test with all ontologies that have an equivalence axiom

**Comment by beckyjackson** [comment]
Migrated to https://github.com/OBOFoundry/Experimental-OBO-Core/issues/23
