### ISSUE TITLE
energy

### ISSUE THREAD

**Issue by cmungall** [rctauber/Experimental-OBO-Core#4]
Currently ENVO is a home for energy. I created the following in https://github.com/EnvironmentOntology/envo/issues/618:

![image](https://user-images.githubusercontent.com/50745/57403530-c0799900-718e-11e9-976e-519635b04ee5.png)

Does core agree with the placement under disposition, and should the root 'energy' be in core?

**Comment by beckyjackson** [comment]
Migrated to https://github.com/OBOFoundry/Experimental-OBO-Core/issues/25
