### ISSUE TITLE
radiation

### ISSUE THREAD

**Issue by cmungall** [rctauber/Experimental-OBO-Core#5]
is radiation with the scope of core?

We have this ENVO just now:

![image](https://user-images.githubusercontent.com/50745/57403890-89f04e00-718f-11e9-99e2-c4da16d93130.png)

See also: https://github.com/EnvironmentOntology/envo/issues/255

**Comment by beckyjackson** [comment]
Migrated to https://github.com/OBOFoundry/Experimental-OBO-Core/issues/26
